import { useState, useEffect } from 'react'
import './App.css'

function App() {
  const [items, setItems] = useState([])
  const [newItemName, setNewItemName] = useState('')
  const [selectedCategory, setSelectedCategory] = useState('')
  const [filterCategory, setFilterCategory] = useState('all')
  const [isLoading, setIsLoading] = useState(false)

  // Predefined categories - you can modify these or fetch from your backend
  const categories = [
    'Fruits',
    'Vegetables',
    'Meat',
    'Drinks'
  ]

  // API base URL - replace with your backend URL
  const API_BASE_URL = 'http://localhost:3001/api' // Change this to your backend URL

  // Fetch items from backend
  const fetchItems = async () => {
    try {
      setIsLoading(true)
      // For now, using localStorage. Replace with actual API call:
      // const response = await fetch(`${API_BASE_URL}/items`)
      // const data = await response.json()
      // setItems(data)
      
      const storedItems = localStorage.getItem('groceryItems')
      if (storedItems) {
        setItems(JSON.parse(storedItems))
      }
    } catch (error) {
      console.error('Error fetching items:', error)
    } finally {
      setIsLoading(false)
    }
  }

  // Add new item
  const addItem = async () => {
    if (!newItemName.trim() || !selectedCategory) {
      alert('Please enter an item name and select a category')
      return
    }

    const newItem = {
      id: Date.now(), // In real app, this would be generated by backend
      name: newItemName.trim(),
      category: selectedCategory,
      completed: false,
      createdAt: new Date().toISOString()
    }

    try {
      setIsLoading(true)
      // Replace with actual API call:
      // const response = await fetch(`${API_BASE_URL}/items`, {
      //   method: 'POST',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify(newItem)
      // })
      // const savedItem = await response.json()
      
      const updatedItems = [...items, newItem]
      setItems(updatedItems)
      localStorage.setItem('groceryItems', JSON.stringify(updatedItems))
      
      setNewItemName('')
      setSelectedCategory('')
    } catch (error) {
      console.error('Error adding item:', error)
    } finally {
      setIsLoading(false)
    }
  }

  // Toggle item completion
  const toggleItem = async (itemId) => {
    try {
      const updatedItems = items.map(item =>
        item.id === itemId ? { ...item, completed: !item.completed } : item
      )
      
      // Replace with actual API call:
      // await fetch(`${API_BASE_URL}/items/${itemId}`, {
      //   method: 'PATCH',
      //   headers: { 'Content-Type': 'application/json' },
      //   body: JSON.stringify({ completed: !items.find(i => i.id === itemId).completed })
      // })
      
      setItems(updatedItems)
      localStorage.setItem('groceryItems', JSON.stringify(updatedItems))
    } catch (error) {
      console.error('Error updating item:', error)
    }
  }

  // Delete item
  const deleteItem = async (itemId) => {
    try {
      // Replace with actual API call:
      // await fetch(`${API_BASE_URL}/items/${itemId}`, { method: 'DELETE' })
      
      const updatedItems = items.filter(item => item.id !== itemId)
      setItems(updatedItems)
      localStorage.setItem('groceryItems', JSON.stringify(updatedItems))
    } catch (error) {
      console.error('Error deleting item:', error)
    }
  }

  // Filter items based on selected category
  const filteredItems = filterCategory === 'all' 
    ? items 
    : items.filter(item => item.category === filterCategory)

  // Load items on component mount
  useEffect(() => {
    fetchItems()
  }, [])

  return (
    <div className="app">
      <div className="app-content">
        <header className="app-header">
          <h1>Groceries Shopping App</h1>
        </header>

        <main className="app-main">
        {/* Add Item Section */}
        <section className="add-item-section">
          <div className="input-group">
            <input
              type="text"
              placeholder="Add a grocery item..."
              value={newItemName}
              onChange={(e) => setNewItemName(e.target.value)}
              onKeyPress={(e) => e.key === 'Enter' && addItem()}
              disabled={isLoading}
            />
            
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              disabled={isLoading}
            >
              <option value="">Select Category</option>
              {categories.map(category => (
                <option key={category} value={category}>{category}</option>
              ))}
            </select>
            
            <button 
              onClick={addItem}
              disabled={isLoading || !newItemName.trim() || !selectedCategory}
            >
              Add Item
            </button>
          </div>
        </section>

        {/* Filter and Actions Section */}
        <section className="filter-section">
          <div className="filter-group">
            <select
              value={filterCategory}
              onChange={(e) => setFilterCategory(e.target.value)}
            >
              <option value="all">Filter Category</option>
              {categories.map(category => (
                <option key={category} value={category}>{category}</option>
              ))}
            </select>
            
            <button onClick={() => setFilterCategory('all')}>
              Show All Items
            </button>
          </div>
        </section>

        {/* Items List Section */}
        <section className="items-section">
          {isLoading && <div className="loading">Loading...</div>}
          
          {!isLoading && filteredItems.length === 0 && (
            <div className="empty-state">
              <p>No items found. Add some groceries to get started!</p>
            </div>
          )}

          {!isLoading && filteredItems.length > 0 && (
            <div className="items-grid">
              {filteredItems.map(item => (
                <div key={item.id} className={`item-card ${item.completed ? 'completed' : ''}`}>
                  <div className="item-content">
                    <h3 className="item-name">{item.name}</h3>
                    <span className="item-category">{item.category}</span>
                  </div>
                  
                  <div className="item-actions">
                    <button
                      className={`toggle-btn ${item.completed ? 'completed' : 'pending'}`}
                      onClick={() => toggleItem(item.id)}
                      title={item.completed ? 'Mark as pending' : 'Mark as completed'}
                    >
                      {item.completed ? '✓' : '○'}
                    </button>
                    
                    <button
                      className="delete-btn"
                      onClick={() => deleteItem(item.id)}
                      title="Delete item"
                    >
                      ×
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>

        {/* Summary Section */}
        {items.length > 0 && (
          <section className="summary-section">
            <div className="summary-stats">
              <span>Total: {items.length}</span>
              <span>Completed: {items.filter(item => item.completed).length}</span>
              <span>Pending: {items.filter(item => !item.completed).length}</span>
            </div>
          </section>
        )}
        </main>
      </div>
      
      <div className="app-illustration">
        <div className="grocery-scene">
          <div className="shopping-bag">
            <div className="bag-body"></div>
            <div className="bag-handles">
              <div className="handle left"></div>
              <div className="handle right"></div>
            </div>
          </div>
          
          <div className="floating-groceries">
            <div className="grocery-item apple">🍎</div>
            <div className="grocery-item banana">🍌</div>
            <div className="grocery-item carrot">🥕</div>
            <div className="grocery-item tomato">🍅</div>
            <div className="grocery-item broccoli">🥦</div>
            <div className="grocery-item orange">🍊</div>
            <div className="grocery-item lettuce">🥬</div>
            <div className="grocery-item pepper">🫑</div>
            <div className="grocery-item grapes">🍇</div>
          </div>
          
          <div className="phone-mockup">
            <div className="phone-screen">
              <div className="phone-header">
                <div className="signal-bars"></div>
                <div className="time">12:30</div>
                <div className="battery"></div>
              </div>
              <div className="app-preview">
                <div className="app-title">Grocery App</div>
                <div className="preview-items">
                  <div className="preview-item">🛒 Fresh Items</div>
                  <div className="preview-item">📱 Easy Shopping</div>
                  <div className="preview-item">🚚 Quick Delivery</div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        <div className="illustration-text">
          <h3>Fresh Groceries! 🥬</h3>
          <p>Shop smart, eat fresh</p>
        </div>
      </div>
    </div>
  )
}

export default App
